### ISSUE TITLE
SignalCoreKit can't compile

### ISSUE THREAD

**Issue by viktorkiver** [signalapp/SignalCoreKit#12]
<img width="1190" alt="Screenshot 2022-07-21 at 12 32 26" src="https://user-images.githubusercontent.com/58690364/180181360-0f5e96cd-f57c-40b5-be6c-3a9230e64a3d.png">

**Comment by max-signal** [comment]
Thanks for reporting. This should be fixed by 5a9c6be791459177328b5da14bf06459e7b79dbb.
