### ISSUE TITLE
SignalCoreKit cannot compile

### ISSUE THREAD

**Issue by omboapp** [signalapp/SignalCoreKit#4]
Refers to a header file which does not exist:

https://github.com/signalapp/SignalCoreKit/commit/7089e60d1600aaed7ebb2fcb2d65d3a90d556090#diff-fa6d73397f5a727adaf608dbbe1cfaf4R6

**Comment by OmarBasem** [comment]
Same issue, @omboapp did you manage to fix it?

**Comment by michelle-signal** [comment]
Sorry for letting this sit so long. We don't usually look at issues reported to our sub-projects.

SignalCoreKit has been steadily compiling for the past few years, so I'm going to call this resolved.
