### ISSUE TITLE
it is not possible to decrypt an attachment without digest

### ISSUE THREAD

**Issue by mertkutluca** [signalapp/SignalCoreKit#5]
https://github.com/signalapp/SignalCoreKit/blob/215afc41654f182bececd949e2410b4a819fbbfb/SignalCoreKit/src/Cryptography.m#L473

**Comment by mertkutluca** [comment]
376th line of Cryptography.m says digest is optional but there is not way to be here with a nil digest

**Comment by michelle-signal** [comment]
Sorry this sat open for so long. Issues on our sub-projects can sometimes sit unnoticed.

But to close the loop here: Digests are required, but may be set nil for old attachment records or old clients. In this case, we'll want to fail the decryption because we don't have the required digest.
